class Lang:
    class EN:
        WINDOW_TITLE = "AutoBuff & AutoClicker v0.1"
        CANCEL = "Cancel"
        OK = "Ok"
        CHOOSE_PROCESS = "Choose the process to buff & click"
        TEST_IT_BUTTON = "Test it!"
        PARTY_MEMBERS = "Party members"
        BUFF_SKILLS = "Buff skill numbers"
        HEAL_BUFF = "Heal buff"
        AUTOBUFF = "Autobuff"
        AUTOCLICKER = "Autoclicker"
        MOUSE_BUTTON = "Mouse button"
        CLICK_DELAY = "Click delay (default skill)"
        DEFAULT_SKILL = "Default skill"
        CLICKER_BUFF_DELAY = "Buff delay with clicker"
        LEFT = "Left"
        MIDDLE = "Middle"
        RIGHT = "Right"
        START = "Start"
        STOP = "Stop"
        EXIT = "Exit"
        ON = "ON"
        OFF = "OFF"

        class Errors:
            MUST_CHOOSE_PROCESS = "You must choose a process to test"
            CANNOT_GET_HANDLER = "Process window not found"
            MUST_SETUP_PARTY = "You must setup the party!"
            MUST_CHOOSE_MOUSE_BUTTON = "You must choose a mouse button to click!"

    class ES:
        WINDOW_TITLE = "AutoBuff & AutoClicker v0.1"
        CANCEL = "Cancelar"
        OK = "Aceptar"
        CHOOSE_PROCESS = "Elija proceso donde buffear & clickear"
        TEST_IT_BUTTON = "Probar!"
        PARTY_MEMBERS = "Miembros del party"
        BUFF_SKILLS = "Nº de skills para buffs"
        HEAL_BUFF = "Buff de curación"
        AUTOBUFF = "Autobuff"
        AUTOCLICKER = "Autoclicker"
        MOUSE_BUTTON = "Botón del mouse"
        CLICK_DELAY = "Retardo en click"
        DEFAULT_SKILL = "Skill por defecto"
        CLICKER_BUFF_DELAY = "Retardo en buffs con clicker activado"
        LEFT = "Izquierdo"
        MIDDLE = "Ruedita"
        RIGHT = "Derecho"
        START = "Encender"
        STOP = "Apagar"
        EXIT = "Salir"
        ON = "ON"
        OFF = "OFF"

        class Errors:
            MUST_CHOOSE_PROCESS = "Debe seleccionar un proceso para testear"
            CANNOT_GET_HANDLER = "No se encontró una ventana abierta del proceso"
            MUST_SETUP_PARTY = "Debe configurar la party!"
            MUST_CHOOSE_MOUSE_BUTTON = "Debe seleccione un botón del mouse para clickear!"
